blockchain/Blockchain-Known-Pools

pools.json

Add Bitsolo

---

pools.json

Maybe this will fix it, don't think github even shows a difference properly, maybe some invisible bit there.

maybe weird encoding causing the problem

---

pools.json

This pool so far has found the following 2 blocks.
https://blockchain.info/block-height/350387
https://blockchain.info/block-height/350405

add BitClub Network Pool

---

pools.json

Last block found by this pool.
https://blockchain.info/block-index/830973

add ckpool solo pool

---

pools.json

This should be the mining pool for http://digitalbtc.com/

add db.high.re pool

---

pools.json

This pool is super inconsistent with coinbase tags and mining addresses, I got a good amount of the more often used addresses and a new tag they seem to use, source https://polmine.pl/?action=statistics

add secondary polmine.pl addresses and coinbase tag

---

pools.json

This pool has 3 stratum servers each mining to a different address.

add Telco 214 pool

---

pools.json

pool34.com is 21 Inc/21E6's mining pool

add 21E6 LLC/21 Inc's pool

---

pools.json

AntPool add new identify strings in coinbase transaction: "/AntPool/".

AntPool add new identify strings

---

pools.json

Adding "myBTCcoin Pool" at mybtccoin.com that just found BLOCK #361937. Thank you.

Add myBTCcoin Pool

---

pools.json

blocks found can be seen here http://8baochi.com/index.php/home/public/minerblock

add 8baochi pool

---

pools.json

Blocks found by this solopool can be seen here http://tbdice.org/blocks.htm

add technobit dice solo pool

---

pools.json

Pool server links no longer work so I've changed those to the company website(telco214.com).

add more telco 214 generation addresses

---

pools.json

looks like this capitalization isn't getting picked up

add missing btcchina pool identifier

---

pools.json

block history here:
http://hashpool.com/stats/history?tab=stratum

add hashpool pool

---

pools.json

This should leave the historical tags intact.

Rename BTCChina Pool to BTCC Pool

---

pools.json

confirmed via stratum decode and this reddit post https://www.reddit.com/r/bitcoinxt/comments/3qixsk/anyone_know_whos_responsible_for_380861/cwfm5mx

add multipool pool

---

pools.json

add transactioncoinmining pool

---

pools.json

Make reference to http://www.a-xbt.com

Add A-XBT company

---

pools.json

Confirmed via stratum decode.
https://blockchain.info/block-index/998216/000000000000000003014d996fb435fa513a092cb86582d9f5954cea15ae6dd9

add Nexious pool

---

pools.json

This block https://blockchain.info/tx/9859c5fbe83b64962e99179ca1b72c72a6d6b594c0b97facbfd9f4bc02db915a
was found by this pool here http://www.bravo-mining.com/index.php?page=statistics&action=pool

add Jonny Bravo's Mining Emporium

---

pools.json

This block https://blockchain.info/block-index/1003902 was found by this pool http://pool.wemine.uk/index.php?page=statistics&action=blocks verified via stratum decode.

add Tricky's BTC Pool

---

pools.json

This block https://blockchain.info/block-index/1004070/00000000000000000213afb64a9f07d2fe04140ea3f86cae3a7b4f30a6297913 was found here http://stratum1.esited.net:8080/stats generation address validated via stratum decoder.

add eSited pool

---

pools.json

The original entry here involved some testing. This is a more proper definition of what the pool is.

Rename eSited pool to Hotpool

---

pools.json

This block https://blockchain.info/tx/3c050714dad26b4dc9c3e40612bfbd08161b8229aa6e1620141b95738ce16d56 was found here https://www.btcmp.com/blocklist verified via stratum decode.

add BTCMP pool

---

pools.json

This block https://blockchain.info/tx/85fecfa69faf271a06546375d9cf8a634f512adea70218b61a5373b54db21f55 was found by this pool here http://www.bcmonster.com/index.php?page=statistics&action=blocks

add BCMonster pool

---

pools.json

This block https://blockchain.info/tx/87f18af02ec9fdc74c0f41b7091d6c9112ece2bb9253184f4737cabc3200f932 was found here http://patelsminingpool.com/BTC/public/index.php?page=statistics&action=blocks

add Patel's Mining Pool

---

pools.json

HaoBTC mining pool is the new launched pool operated by HaoBTC.

Add HaoBTC mining pool tag

---

pools.json

add BTCPool

---

pools.json

Added pool.bitcoin.com

---

pools.json

This is a new pool currently in testing that found its first block here https://blockchain.info/tx/8191bcc40a94cc75e5c167278dbe50bd07b8aac7c38df621eb1571c6a32ded1c

add Bitcoin India mining pool

---

pools.json

Possible fix for [this issue](https://github.com/blockchain/Blockchain-Known-Pools/issues/96).

add generation address for Bitcoin India

---

pools.json

Last block found https://blockchain.info/tx/50244248963a3f580e3953819db37a50607e1964b035c2821a25b329696c12cc
Only operator of the pool is known.

add pool operated by shawnp0wers

---

pools.json

This pool mined a block [here](https://blockchain.info/tx/c50f97f13e140aa69fa7df45b68fb5a554419b316fa403158bb65d2a6f269b5f). Generation address confirmed via stratum decode.

add BATPOOL pool

---

pools.json

Took a long time. 562 lines of scrolling pays off.

Remove Slashes

---

pools.json

This [block](https://blockchain.info/tx/56e00c845c28fb19690d48354eb7deb653a828545aaeb41e72c042474034874e) was found [here](https://ekanembtc.com/index.php?page=statistics&action=blocks). Verified via stratum decode.

add EkanemBTC pool

---

pools.json

Some [recent blocks](https://blockchain.info/block/000000000000000001b2d4493d49e20f905d72934030bb8e60a4e70588347d67) are mining to the new address 1BUhwvF9oo3qkaSjjPpWrUzQxXNjkHdMZF as well as known telco 214 address 18hvMLisvfc58PvA5rHH7NsLN9CV5ddB2x

add new Telco 214 address

---

pools.json

Looks like [this block](https://blockchain.info/tx/ddc5acd9ac62e9f60caaefea29caf03adfcafbae0280df9ead76b5dcbb6aca57) was found by this new pool.

Add waterhole pool

---

pools.json

[This block](https://blockchain.info/tx/7dc0c3731a52140840b26fa7ce0873fa4582698934ba02c3a5d2ef4e5341da15) was found by BitcoinRussia looks like.

Add BitcoinRussia Pool

---

pools.json

Looks like this pool found [this](https://blockchain.info/tx/8dfff5f7055136060e6a9156543ff8580ff2144a210c6bbaa3e593542acb65cc) block.

Add 7pool mining pool.

---

pools.json

This is a new pool for mining multiple digital coins, small but growing smoothly. Thanks!

please add DCEX pool

---

pools.json

[This](https://blockchain.info/tx/6173008990be73406c2d364e2a3f388fdbc6402a43cd33dddda4524d7e3bc5f9) block was found by this pool.

Add ckpool SPLNS pool

---

pools.json

Added HTTPS to main pools links when possible

Added HTTPS to main pools links when possible

---

pools.json

Add a new pool '58COIN', a new block is mined by this pool which could be check the url:
https://blockchain.info/block/0000000000000000007dde611587196d8704ca76ecc5a04a90f22023e70f8a57

add a new pool '58COIN' and the block 493228 is mined by this pool

---

pools.json

Multipool - currently supported: LTC, BTC, DASH 
Asic boost support.
One of our latest blocks: https://blockchair.com/bitcoin/block/0000000000000000003296073e8f9e2ea837ec817fe2138b86368bc266529ae4

Added SigmaPool.com

---

pools.json

Adding SBI Crypto to pool list with two variations of tagging.

Add SBI Crypto to pools list
