blockchain/Blockchain-Known-Pools

- pools.json
This seems to be the only consistent address this pool pays out to. They have found 1 block so far and only the 1PmRrdp1YSkp1LxPyCfcmBHDEipG5X4eJB fee address matches what they are currently mining to as the other two addresses are different.
https://blockchain.info/tx/ae05491d46b5f80feb6cb520921bf09db7be12ccb62a3a5b1cf8f835d588c465
Current decoded stratum payout split:
Coinbase output: 2448154112 -- 16NonTeX4Wy42SdYJrgL5QW77WBHquPJns
Coinbase output:   50477404 -- 1JffQu8WzPqn3bqKKF159iAG3mjpEtQroF
Coinbase output:   25238702 -- 1PmRrdp1YSkp1LxPyCfcmBHDEipG5X4eJB
> add BTC Pool Party pool

- pools.json
This pool seems to be active with only a small amount of hashrate but has found historical blocks, address confirmed via https://btcdig.com/stats/blocks/ and stratum decoder.
> add btcdig pool

- pools.json
Based on [this latest block](https://blockchain.info/tx/6cfab7be7159adcc98be20985d604352903dc3526ddc3cdcb5d935a4be39f985) the coinbase tag is "/A-XBT/" and not "axbt".
> Fix A-XBT Coinbase tag

- pools.json
Looks like 21 Inc is now using a new generation address, coins from the previous known address(1CdJi2xRTXJF6CEJqNHYyQDNEcM3X7fUhD) were swept through this address.
> add new 21 Inc address

- pools.json
Stratum decode of sha.eobot.com:3333 matches generation address 1MPxhNkSzeTNTHSZAibMaS8HS1esmUL1ne in this block https://blockchain.info/tx/b9ffd00b7ef592a062213f38ebae51e5140672ee563227cbd2d61e24e427013a
> add Eobot pool

- pools.json
some block such as this one https://blockchain.info/tx/a223e91050bab7ac0e4fa01d1df2980be9fcdc0fe9ba6407c178966aab7b3ec4 aren't getting picked up
> add alternative bitfury coinbase sig

- pools.json
[This](https://blockchain.info/tx/59e7532c046ed825683306d6498d886209de02d412dd3f1dc55c55f87ea1c516) block was mined by 1hash.com. Note that the tag is an OP_RETURN of the generation transaction. The OP_RETURN decoded contains the string "Mined by 1hash.com". Blocktrail appears to decode the OP_RETURN properly [here](https://www.blocktrail.com/BTC/tx/59e7532c046ed825683306d6498d886209de02d412dd3f1dc55c55f87ea1c516#tx_messages) while blockchain.info only says "Unable to decode output address".
Transaction:
```json
{
"txid": "59e7532c046ed825683306d6498d886209de02d412dd3f1dc55c55f87ea1c516",
"size": 135,
"version": 1,
"locktime": 0,
"vin": [
{
"coinbase": "03c61e06",
"sequence": 4294967295
}
],
"vout": [
{
"value": 25.76452213,
"n": 0,
"scriptPubKey": {
"asm": "OP_DUP OP_HASH160 …
```
> add 1Hash pool

- pools.json
Not sure which organization runs this pool but the block finds are [here](http://199.115.116.7:8925/api/getblocksstats). Verified via stratum decode as well. Block finds on blockchain.info are [here](https://blockchain.info/address/1BRY8AD7vSNUEE75NjzfgiG18mWjGQSRuJ).
> add UNOMP pool

- pools.json
This pool seems to be using two generation addresses, last block was mined to this address https://blockchain.info/tx/e67fc7ddd1ab8dce095be3a1965cefbfd59c3cc38d76ddac58fbb4b556ef5dc9
> add secondary address for Patel's Mining pool

- pools.json
Here is a couple of examples of the coinbase data in ViaBTC blocks:
- h4/ViaBTC/Via Bitcoin Making The World a Better Place/H!
- Nh&/ViaBTC/viabtc.com is accessible now./8ve:
> Fix ViaBTC tag

- pools.json
Added btcsig for new pool: gbminers.com
Link on blockchain.info: https://blockchain.info/blocks/52.66.51.105
Block found by the pool: https://blockchain.info/block-height/427549
Current Hash Rate of the pool: 9 PH/s
> Added gbminers pool

- pools.json
Hi, we just rebrand from `BTCPool` to `BTC.com`.
> rebrand pool.btc.com

- pools.json
Confirmed new sha.eobot.com:3333 generation address matches 16GsNC3q6KgVXkUX7j7aPxSUdHrt1sN2yN via stratum decode.
> add new Eobot address

- pools.json
Block found by phash.io:
https://blockchain.info/tx/78d236bb3c099108c066bd1382f1215372336f21c1fef736b4c4a5c79ed43664
[Previous](https://blockchain.info/tx/cb3673b21a453b850d2cf4f9f6b45a3eaa4a6d7acef7cc3aaad8e40e2a4c397f) blocks that used phash.cn coinbase tag were [swept](https://blockchain.info/tx/4beffbbfe921acda8d70823f218211ba7dacc844ebe94ea389fd6fa8c49c23a3) into the phash.io generation address.
> add phash.io pool

- pools.json
This is not confirmed personally but there are [reports](https://www.reddit.com/r/btc/comments/52qaxb/nobody_noticed_but_as_there_are_new_bip109_miners/d7mspgp/) that this is the pool for [KNC's new owner](http://www.coindesk.com/knc-miner-acquisition-gogreenlight/).
> add GoGreenLight pool

- pools.json
Seeing blocks being found with btc.cop in coinbase sig.
https://blockchain.info/tx/d662de853b1b39ac486021b41ac53e3fedf0bdddae1e4f3278c37e8928300be6
> add BTC.TOP pool

- pools.json
This pool found a block [here](https://blockchain.info/tx/71c78325f31c70c943912da030cc0683859467591b06fc242ab8ad1e5c03a41b).
Generation transaction decode of stratum.connectbtc.com:3333 is:
```json{
"txid": "20831cbfb5398af516e4c5bf0c86b99ad21def989f562062e514504ac7850f66",
"hash": "20831cbfb5398af516e4c5bf0c86b99ad21def989f562062e514504ac7850f66",
"version": 1,
"locktime": 0,
"vin": [
{
"coinbase": "03bcca064b1a37de000000002f436f6e6e656374425443202d20486f6d6520666f72204d696e6572732f",
"sequence": 16777215
}
],
"vout": [
{
"value": 12.55238159,
"n": 0,
"scriptPubKey": {
"asm": "OP_DUP OP_HASH160 c9af3e308a3f540a81800ea3785bfcfb0ad2735b OP_EQUALVERIFY OP_CHECKSIG",
"hex": "76a914c9af3e308a3f540a81800ea3785bfcfb0ad2735b88ac",
"reqSigs": 1,
"type": "pubkeyhash",
"addresses": [ …
```
> add ConnectBTC mining pool

- pools.json
should some blocks like [this one](https://blockchain.info/tx/3753472365a4030549502c0030d84c249c11bdd34683144236796e026aa61604) getting missed
> add btc.com coinbase sig detection

- pools.json
The 18hvMLisvfc58PvA5rHH7NsLN9CV5ddB2x address in [this block](https://blockchain.info/tx/c1c469741f9d1beff0354e348090ff1a30d74c47b5d75b897e21c4f9fb57d3b1) is a [Telco 214 wallet address](https://www.walletexplorer.com/wallet/Telco214?from_address=18hvMLisvfc58PvA5rHH7NsLN9CV5ddB2x) so we can assume these blocks are likely mined by Telco 214.
> Add new Telco 214 addresses

- pools.json
Pool mined [this](https://blockchain.info/tx/db3398a48256dc74a88062d55016b82d4268bb8ad727cf43c42fea72f4c385bb) block, verified via stratum decode of stratum.canoepool.com:3333.
> add CANOE pool

- pools.json
This pool has found one [block](https://blockchain.info/tx/524fae17bb776cd86760202f029f003c3c51fea4197d2cac116fa37164907af9) Coinbase sig was changed afterward, which verified via stratum decoder to be "/RigPool.com/". The sig listed on the website("/RigPool/") is incorrect.
> add rigpool

- pools.json
The [latest block](https://blockchain.info/tx/982eedb47db0ec3b0c2045ac036951c7592ea6bc6ac0a0e2bcba08cdcffc7986) by this pool didn't have the coinbase tag for some reason.
> add BCMonster generation address tagging

- pools.json
Looks like this pool mined a few [blocks](https://blockchain.info/tx/41e43f7c00b106ccc95b9c20bbca9375fe7377a541ca15fffe6bb61809dd38c3) recently. I wasn't able to find a public stratum URL to get a decode off of but it should be correct based off of the coinbase sig.
> add Apool pool

- pools.json
[This](https://miningkings.com/index.php?k=pblocks) is the blockpage for this pool, confirmed via stratum decode as well. And yes the [blocks](https://blockchain.info/tx/2b13a24cf84f8364ad551f8e7ce610ef72371ce2911482a259d3fb4d6ff44a8d) really do use the coinbase sig `/mined by poopbut/`.
> Add MiningKings pool
